"""added enums for permissions

Revision ID: 16a575a48a39
Revises: 384b9a78b1c1
Create Date: 2025-04-24 13:58:19.710444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16a575a48a39'
down_revision: Union[str, None] = '384b9a78b1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('database', sa.Enum('ROLES', 'DISCIPLINES', 'USERS', 'GRADES', name='databasesenum'), nullable=False))
    op.add_column('permissions', sa.Column('permission_type', sa.Enum('READ', 'UPDATE', 'DELETE', 'CREATE', name='permissionsenum'), nullable=False))
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.drop_column('permissions', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    op.drop_column('permissions', 'permission_type')
    op.drop_column('permissions', 'database')
    # ### end Alembic commands ###
