---
services:
  postgres:
    image: postgres:15
    container_name: postgres_virt_dekanat
    ports:
      - '${POSTGRES_PORT:-7401}:5432'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-pass}'
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_DB: '${POSTGRES_DB:-postgres}'
    volumes:
      - ./temp:/var/lib/postgresql/data
  backend:
    build:
      dockerfile: ./deploy/docker/Dockerfile
      context: .
    container_name: virt_dekanat_backend
    ports:
      - '7400:7400'
    volumes:
      - ./temp:/backend/data
    depends_on:
      - postgres
