---
services:
  postgres:
    image: postgres:15
    container_name: postgres_virt_dekanat
    ports:
      - '${POSTGRES_PORT:-7401}:5432'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-pass}'
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_DB: '${POSTGRES_DB:-postgres}'
    volumes:
      - ./temp:/var/lib/postgresql/data

