---
services:
  postgres:
    image: postgres:15
    container_name: postgres_virt_dekanat
    ports:
      - '${POSTGRES_PORT:-7401}:5432'
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-pass}'
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_DB: '${POSTGRES_DB:-postgres}'
    volumes:
      - ./temp:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: ./deploy/docker/Dockerfile
      context: .
    container_name: virt_dekanat_backend
    ports:
      - '7400:7400'
    volumes:
      - ./temp:/backend/data
    depends_on:
      - postgres
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "7410:9090"
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    ports:
      - "7420:3100"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./fastapi-app:/var/log/fastapi
      - ./promtail-config.yml:/etc/promtail/config.yml
    networks:
      - monitoring
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "7430:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data:
