"""grade type field

Revision ID: 3a13e2f660fd
Revises: 53e7d3ec368a
Create Date: 2025-05-27 12:22:36.810043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a13e2f660fd'
down_revision: Union[str, None] = '53e7d3ec368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('type', sa.Enum('MODULE1', 'MODULE2', 'ZACHET', 'EXAM', name='gradeenum'), server_default='MODULE1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'type')
    # ### end Alembic commands ###
