"""grade type enum

Revision ID: 53e7d3ec368a
Revises: 25c20c27e097
Create Date: 2025-05-27 12:17:38.342647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53e7d3ec368a'
down_revision: Union[str, None] = '25c20c27e097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    type = postgresql.ENUM('MODULE1', 'MODULE2', 'ZACHET', 'EXAM', name='gradeenum')
    type.create(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    type = postgresql.ENUM('MODULE1', 'MODULE2', 'ZACHET', 'EXAM', name='gradeenum')
    type.drop(op.get_bind())
    # ### end Alembic commands ###
