"""grades rels and professor discipline rel

Revision ID: 6d95bd687aae
Revises: 33e352a9fdce
Create Date: 2025-05-25 21:27:38.447144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d95bd687aae'
down_revision: Union[str, None] = '33e352a9fdce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor_disciplines',
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('professor_id', 'discipline_id')
    )
    op.add_column('grades', sa.Column('student_id', sa.Integer(), nullable=False))
    op.add_column('grades', sa.Column('professor_id', sa.Integer(), nullable=False))
    op.add_column('grades', sa.Column('discipline_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'grades', 'professors', ['professor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_column('grades', 'discipline_id')
    op.drop_column('grades', 'professor_id')
    op.drop_column('grades', 'student_id')
    op.drop_table('professor_disciplines')
    # ### end Alembic commands ###
