"""Added group model

Revision ID: fe34495a5aa0
Revises: bc8a0f6609e2
Create Date: 2025-05-25 20:02:44.564551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe34495a5aa0'
down_revision: Union[str, None] = 'bc8a0f6609e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'disciplines', ['discipline_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciplines', type_='unique')
    # ### end Alembic commands ###
